### ISSUE TITLE
Add a make/mage file to automate the tasks

### ISSUE THREAD

**Issue by jcchavezs** [VermaShivansh/coraza-ratelimit-plugin#1]
It should be trivial to run the tests (unit and e2e) with a single command. mage is a good option as we use it in all coraza projects but it is also possible to use make.

**Comment by VermaShivansh** [comment]
Hey @jcchavezs , I have added a magefile that helps in executing tests in the following PR #5. Please have a look and suggest improvements. 
Also, should I have different mage targets for different test cases?
