### ISSUE TITLE
Is it possible to do rate limiting on unkown values?

### ISSUE THREAD

**Issue by jcchavezs** [VermaShivansh/coraza-ratelimit-plugin#3]
Use case:

I want to accept only 100rps/s per header `:authority` which I don't know on beforehand.

**Comment by VermaShivansh** [comment]
Hey @jcchavezs,
I considered a few cases.

**1**.  I am sending a header with authority in the request that has no value. 
In the following case, after macro expansion, I receive an empty string which is handled in following way.

![image](https://github.com/VermaShivansh/coraza-ratelimit-plugin/assets/75882684/6c840283-325a-4cbb-a2d7-63e478126fb3)

and ratelimit struct looks like this 

![image](https://github.com/VermaShivansh/coraza-ratelimit-plugin/assets/75882684/9af2517d-13be-4e06-a576-18bf8fe6c846)

**Conclusion:-** A header with name 'authority' with no value is put in 'misc' zone.



**2.** I am sending a header with authority in request that has a value.
Works lika a charm as expected.

![image](https://github.com/VermaShivansh/coraza-ratelimit-plugin/assets/75882684/caf331cd-ab31-434d-ba7e-61079e86757b)



**3.** I am not even sending that header at all. In this case macro expansion returns the same macro name. Suppose if my macro name was `${REQUEST_HEADERS.authority}` and I haven't sent any header with name authority, then macro expansion returns value as REQUEST_HEADERS.authority, therefore zone name is the same and ratelimit object looks like this.

![image](https://github.com/VermaShivansh/coraza-ratelimit-plugin/assets/75882684/9f9acb2a-13a1-476b-a10d-eb1db148913e)

Is this acceptable behaviour, should we handle it differently or this is fine?
